# Generated by Django 3.0.6 on 2020-05-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=14),
        ),
    ]
