# Generated by Django 3.0.6 on 2020-05-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='Centro', max_length=200),
        ),
    ]
